version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "monthly"

    open-pull-requests-limit: 10

    groups:
      production-version-updates:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "*"

      development-version-updates:
        applies-to: "version-updates"
        dependency-type: "development"
        patterns:
          - "*"

      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
